/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jinye_demo_jidub_MainActivity */

#ifndef _Included_jinye_demo_jidub_MainActivity
#define _Included_jinye_demo_jidub_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jinye_demo_jidub_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jinye_demo_jidub_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     jinye_demo_jidub_MainActivity
 * Method:    toolAdditionFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jinye_demo_jidub_MainActivity_toolAdditionFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
